version: '3.4'

services:
  thecodecovecards:    
    image: brayonderoy/the-code-cove-cards
    ports:
      - '5000:5000'
      - '443:443'
    build:
      context: ./
      dockerfile: production.dockerfile