
export const BLACK_CARD_ID = 1;
export const WHITE_CARD_ID = 2;

export const GET_CARDS_PENDING = "GET_CARDS_PENDING";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";

export const RESET_CARDS = "RESET_CARDS";

export const SELECT_CARD = "SELECT_CARD";

export const SET_SELECTED_CARD_COUNT = "SET_SELECTED_CARD_COUNT";

export const SEND_SELECTED_CARDS_PENDING = "SEND_SELECTED_CARDS_PENDING";
export const SEND_SELECTED_CARDS_SUCCESS = "SEND_SELECTED_CARDS_SUCCESS";
export const SEND_SELECTED_CARDS_FAILURE = "SEND_SELECTED_CARDS_FAILURE";

export const CHECK_ANY_CARDS_SELECTED_PENDING = "CHECK_ANY_CARDS_SELECTED_PENDING";
export const CHECK_ANY_CARDS_SELECTED_SUCCESS = "CHECK_ANY_CARDS_SELECTED_SUCCESS";
export const CHECK_ANY_CARDS_SELECTED_FAILURE = "CHECK_ANY_CARDS_SELECTED_FAILURE";

export const GET_SELECTED_PLAYER_CARDS_PENDING = "GET_SELECTED_PLAYER_CARDS_PENDING";
export const GET_SELECTED_PLAYER_CARDS_SUCCESS = "GET_SELECTED_PLAYER_CARDS_SUCCESS";
export const GET_SELECTED_PLAYER_CARDS_FAILURE = "GET_SELECTED_PLAYER_CARDS_FAILURE";

export const DELETE_USED_CARDS_PENDING = "DELETE_USED_CARDS_PENDING";
export const DELETE_USED_CARDS_SUCCESS = "DELETE_USED_CARDS_SUCCESS";
export const DELETE_USED_CARDS_FAILURE = "DELETE_USED_CARDS_FAILURE";

export const REMOVE_USED_CARDS = "REMOVE_USED_CARDS";

export const SETUP_NEXT_ROUND_PENDING = "SETUP_NEXT_ROUND_PENDING";
export const SETUP_NEXT_ROUND_SUCCESS = "SETUP_NEXT_ROUND_SUCCESS";
export const SETUP_NEXT_ROUND_FAILURE = "SETUP_NEXT_ROUND_FAILURE";

export const GET_BLACK_CARD_PENDING = "GET_BLACK_CARD_PENDING";
export const GET_BLACK_CARD_SUCCESS = "GET_BLACK_CARD_SUCCESS";
export const GET_BLACK_CARD_FAILURE = "GET_BLACK_CARD_FAILURE";

export const RESET_SELECTED_CARDS = "RESET_SELECTED_CARDS";

export const REMOVE_SELECTED_CARDS = "REMOVE_SELECTED_CARDS";