
export const BLACK_CARD_ID = 1;
export const WHITE_CARD_ID = 2;

export const GET_CARDS_PENDING = "GET_CARDS_PENDING";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";

export const RESET_CARDS = "RESET_CARDS";

export const SELECT_CARD = "SELECT_CARD";

export const SET_SELECTED_CARD_COUNT = "SET_SELECTED_CARD_COUNT";



