

export const ADD_GAME_PENDING = 'ADD_GAME_PENDING';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';

export const GET_GAME_PENDING = 'GET_GAME_PENDING';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_FAILURE = 'GET_GAME_FAILURE';

export const REMOVE_GAME_PENDING = 'REMOVE_GAME_PENDING';
export const REMOVE_GAME_SUCCESS = 'REMOVE_GAME_SUCCESS';
export const REMOVE_GAME_FAILURE = 'REMOVE_GAME_FAILURE';

export const FETCH_GAMES_PENDING = 'FETCH_GAMES_PENDING';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const SET_GAME = 'SET_GAME';

export const CHECK_USER_TURN_PENDING = "CHECK_USER_TURN_PENDING";
export const CHECK_USER_TURN_SUCCESS = "CHECK_USER_TURN_SUCCESS";
export const CHECK_USER_TURN_FAILURE = "CHECK_USER_TURN_FAILURE";